services:
  registry:
    image: 'eclipsebasyx/aas-registry-log-mem:2.0.0-milestone-02'
    container_name: 'registry'
    ports:
      - 8080:8080
  aas1:
    image: 'eclipsebasyx/aas-environment:2.0.0-milestone-02'
    container_name: 'aas1'
    ports:
      - 8081:8081
    volumes:
      - ./aas.properties:/application/application.properties
      - ./AASx7.aasx:/application/aas/AASx7.aasx
