version: '3.8'
services:
  mongoServer:
    image: mongo:latest
    container_name: mymongodb
    ports:
      - '27017:27017'
    volumes:
      - '/Users/tom/Documents/AWI Msc./2. Semester/Business Process Automation/bpa-beleg-ss24/Mongo:/data'
    networks:
      - mg_net
  mongoExpress:
    image: mongo-express:latest
    container_name: mongoexpress
    depends_on:
      - mongoServer
    ports:
      - '8081:8081'
    environment:
     - ME_CONFIG_MONGODB_SERVER=mongoServer
    networks:
      - mg_net
 
networks:
  mg_net:
    driver: bridge


    
